export const enum ATTACK_TYPE {
  MAGICAL = 'ATTACK_TYPE_MAGICAL',
  PHYSICAL = 'ATTACK_TYPE_PHYSICAL',
}

export const enum DEBUFF_TYPE {
  NONE = 'DEBUFF_TYPE_NONE',
  STUN = 'DEBUFF_TYPE_STUN',
  SLOW_A = 'DEBUFF_TYPE_SLOW_A',
  SLOW_B = 'DEBUFF_TYPE_SLOW_B',
  SLOW_C = 'DEBUFF_TYPE_SLOW_C',
  SLOW_D = 'DEBUFF_TYPE_SLOW_D',
  SLOW_E = 'DEBUFF_TYPE_SLOW_E',
  DEFENCE_REDUCE = 'DEBUFF_TYPE_DEFENCE_REDUCE',
}
