export const LOCATION_PADDING = 0.2
export const enum TOWER_GRADE {
  NORMAL = 'TOWER_GRAMDE_NORMAL',
  MAGIC = 'TOWER_GRAMDE_MAGIC',
  RARE = 'TOWER_GRAMDE_RARE',
  ETC = 'TOWER_GRAMDE_ETC',
  RUIN = 'TOWER_GRAMDE_RUIN',
  HERO = 'TOWER_GRAMDE_HERO',
  BEAST = 'TOWER_GRAMDE_BEAST',
  CREATE = 'TOWER_GRAMDE_CREATE',
  UNIQUE = 'TOWER_GRAMDE_UNIQUE',
  HIDDEN = 'TOWER_GRAMDE_HIDDEN',
  LEGEND = 'TOWER_GRAMDE_LEGEND',
  SPECIAL = 'TOWER_GRAMDE_SPECIAL',
  LIMIT = 'TOWER_GRAMDE_LIMIT',
  ELITE = 'TOWER_GRAMDE_ELITE',
  EPIC = 'TOWER_GRAMDE_EPIC',
  INFINITE = 'TOWER_GRAMDE_INFINITE',
}
