export { default as ATower } from '@/components/Tower/magic/ATower'
export { default as BTower } from '@/components/Tower/magic/BTower'
export { default as CTower } from '@/components/Tower/magic/CTower'
export { default as DTower } from '@/components/Tower/magic/DTower'
export { default as ETower } from '@/components/Tower/magic/ETower'
export { default as FTower } from '@/components/Tower/magic/FTower'
export { default as GTower } from '@/components/Tower/magic/GTower'
export { default as HTower } from '@/components/Tower/magic/HTower'
