export { default as ATower } from '@/components/Tower/hero/ATower'
export { default as BTower } from '@/components/Tower/hero/BTower'
export { default as CTower } from '@/components/Tower/hero/CTower'
export { default as DTower } from '@/components/Tower/hero/DTower'
export { default as ETower } from '@/components/Tower/hero/ETower'
export { default as FTower } from '@/components/Tower/hero/FTower'
export { default as GTower } from '@/components/Tower/hero/GTower'
